---
ci_cd_namespace: omp-ci-cd
dev_namespace: omp-dev
test_namespace: omp-test
app_name: omp-backend

build_vars:
  NAME: '{{ app_name }}'
  GIT_URL: https://github.com/rht-labs/open-management-portal-backend.git
  GIT_REF: master
  PUSH_SECRET: quay-registry-secret
  OUTPUT_IMAGE_NAME: '{{ app_name }}'
  OUTPUT_IMAGE_TAG: latest
  BUILDER_IMAGE_NAME: registry.access.redhat.com/fuse7/fuse-java-openshift
  BUILDER_IMAGE_TAG: 1.5

pipeline_vars:
  PIPELINE_SOURCE_REPOSITORY_URL: https://github.com/rht-labs/open-management-portal-backend.git
  PIPELINE_SOURCE_REPOSITORY_REF: master
  NAME: '{{ app_name }}'

dev_vars:
  NAME: '{{ app_name }}'
  IMAGE_NAME: '{{ app_name }}'
  IMAGE_TAG: latest
  JWT_PUBLIC_KEY_URL: http://sso-cluster-internal:8080/auth/realms/omp/protocol/openid-connect/certs

test_vars:
  NAME: '{{ app_name }}'
  IMAGE_NAME: '{{ app_name }}'
  IMAGE_TAG: latest
  JWT_PUBLIC_KEY_URL: http://sso-cluster-internal:8080/auth/realms/omp/protocol/openid-connect/certs

openshift_cluster_content:
- object: '{{ app_name }}'
  content:
  - name: pipeline
    template: 'https://raw.githubusercontent.com/redhat-cop/openshift-templates/v1.4.15/jenkins-pipelines/jenkins-pipeline-template-with-ocp-triggers.yml'
    params_from_vars: '{{ pipeline_vars }}'
    namespace: '{{ ci_cd_namespace }}'
    tags: 
    - pipeline
  - name: build
    template: '{{ inventory_dir }}/../templates/build.yml'
    params_from_vars: '{{ build_vars }}'
    tags:
      - build
  - name: deployment
    template: '{{ inventory_dir }}/../templates/deploy.yml'
    params_from_vars: '{{ dev_vars }}'
    namespace: '{{ dev_namespace }}'
    tags:
      - deploy
      - dev
  - name: deployment
    template: '{{ inventory_dir }}/../templates/deploy.yml'
    params_from_vars: '{{ test_vars }}'
    namespace: '{{ test_namespace }}'
    tags:
      - deploy
      - test
