name: omp-backend
development: true

servicePort: 8080

imageName: "omp-backend"
imageTag: "latest"

builderImage: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
builderImageTag: 1.8

git:
  uri: https://github.com/rht-labs/open-management-portal-backend.git
  ref: master

ompGitlabApiUrl: http://omp-git-api:8080
jwtPublicKeyLocation: false
jwtIssuer: false
jwtEnable: true
mongodbServiceName: omp-backend-mongodb
mongodbUser: mongouser
mongodbPassword: mongopassword
mongodbDatabase: engagements
mongodbAdminPassword: mongoadminpassword
